WebApp/Areas/Admin/Controllers/QuestionController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.IRepository;
using Microsoft.AspNetCore.Authorization;
using Utility.Constants;
using Services.Contracts;
using Entities.ViewModels;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class QuestionController : Controller
    {
        private readonly IServiceManager _manager;

        public QuestionController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var questions = _manager.QuestionService
                .GetAllQuestions(trackChanges: false, includeProperties: "Quiz").ToList();
            return View(questions);
        }

        public IActionResult GetQuestions(Guid id)
        {
            List<Question> quizQuestions = _manager.QuestionService
                .GetAllQuestions(false)
                .Where(q => q.QuizID.Equals(id))
                .ToList();
            TempData["quizId"] = id;
            return View(quizQuestions);
        }

        public IActionResult Create([FromRoute] Guid id)
        {
            return View(new QuestionViewModel() { QuizId = id});
        }

        [HttpPost]
        public IActionResult Create([FromForm] QuestionViewModel qvm)
        {
            Question question = new Question()
            {
                QuizID = qvm.QuizId,
                QuestionText = qvm.QuestionText,
                OptionA = qvm.OptionA,
                OptionB = qvm.OptionB,
                OptionC = qvm.OptionC,
                OptionD = qvm.OptionD,
                OptionE = qvm.OptionE
            };
            _manager.QuestionService.CreateOneQuestion(question);
            return RedirectToAction(nameof(GetQuestions), new { id = question.QuizID });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var questionToBeDeleted = _manager.QuestionService.GetOneQuestion(id, false);
            if(questionToBeDeleted == null)
            {
                return Json(new { success = false, message = "Silerken bir hata oluştu. Tekrar deneyiniz." });
            }

            _manager.QuestionService.DeleteOneQuestion(id);

            return Json(new { success = true, message = "Silme işlemi başarılı." });
        }
    }
}

WebApp/Areas/Admin/Controllers/QuizController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.IRepository;
using Entities.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using Utility.Constants;
using Services.Contracts;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class QuizController : Controller
    {
        private readonly IServiceManager _manager;

        public QuizController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            List<Quiz> quizzes = _manager.QuizService
                .GetAllQuiz(trackChanges: false, includeProperties: "Questions")
                .ToList();
            return View(quizzes);
        }

        public IActionResult Create()
        {
            return View(new QuizViewModel());
        }

        [HttpPost]
        public IActionResult Create(QuizViewModel quizViewModel)
        {
            if (ModelState.IsValid)
            {
                Question question = new Question()
                {
                    QuestionText = quizViewModel.Question.QuestionText,
                    OptionA = quizViewModel.Question.OptionA,
                    OptionB = quizViewModel.Question.OptionB,
                    OptionC = quizViewModel.Question.OptionC,
                    OptionD = quizViewModel.Question.OptionD,
                    OptionE = quizViewModel.Question.OptionE
                };
                Quiz quiz = new Quiz()
                {
                    Name = quizViewModel.Quiz.Name,
                    CreatedBy = quizViewModel.Quiz.CreatedBy
                };
                quiz.Questions.Add(question);
                _manager.QuizService.CreateOneQuiz(quiz);
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

WebApp/Areas/AppUser/Controllers/UserController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using System.Security.Claims;
using Utility.Constants;

namespace WebApp.Areas.AppUser.Controllers
{
    [Area("AppUser")]
    [Authorize(Roles = Roles.User)]
    public class UserController : Controller
    {
        private readonly IServiceManager _manager;

        public UserController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ApplicationUser appUser = _manager.ApplicationUserService.GetOneAppUsers(userId, false);
            TempData["Name"] = appUser.FirstName + " " +appUser.LastName;
            return View();
        }

        public IActionResult ScoreTable(Guid id)
        {
            List<QuizResult> quizResult = _manager.QuizService.GetOneQuiz(id, false, "QuizResults").QuizResults.ToList();
            return View(quizResult);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-body-tertiary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Anket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        @{
                            if (User.IsInRole(Roles.User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" asp-area="AppUser" asp-controller="User" asp-action="Index">
                                    Ana sayfa
                                        <span class="visually-hidden">(current)</span>
                                    </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    Anketler</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="AppUser" asp-controller="Quiz" asp-action="Create">
                                            Anket oluştur
                                        </a>
                                        <a class="dropdown-item" asp-area="AppUser" asp-controller="Quiz" asp-action="Index">
                                            Anketlerim
                                        </a>
                                    </div>
                                </li>
                            }
                            else if (User.IsInRole(Roles.Admin))
                            {
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Quiz" asp-action="Index">Ana sayfa</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>

                            }
                        }

                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Quiz" asp-action="Index">Anketler</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Question" asp-action="Index">Sorular</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/question.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>